<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGwoi5jG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGwoi5jG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGwoi5jG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGwoi5jG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGwoi5jG\App_KernelDevDebugContainer([
    'container.build_hash' => 'Gwoi5jG',
    'container.build_id' => '6aeffc88',
    'container.build_time' => 1677623127,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGwoi5jG');
