<?php

namespace ContainerGwoi5jG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X9u6lSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.X9u6l_s' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.X9u6l_s'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\BilletController::delete' => ['privates', '.service_locator.LjkgWYe', 'get_ServiceLocator_LjkgWYeService', true],
            'App\\Controller\\BilletController::edit' => ['privates', '.service_locator.LjkgWYe', 'get_ServiceLocator_LjkgWYeService', true],
            'App\\Controller\\BilletController::index' => ['privates', '.service_locator.0c77nnS', 'get_ServiceLocator_0c77nnSService', true],
            'App\\Controller\\BilletController::new' => ['privates', '.service_locator.0c77nnS', 'get_ServiceLocator_0c77nnSService', true],
            'App\\Controller\\BilletController::show' => ['privates', '.service_locator.HCgIJYh', 'get_ServiceLocator_HCgIJYhService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\BilletController:delete' => ['privates', '.service_locator.LjkgWYe', 'get_ServiceLocator_LjkgWYeService', true],
            'App\\Controller\\BilletController:edit' => ['privates', '.service_locator.LjkgWYe', 'get_ServiceLocator_LjkgWYeService', true],
            'App\\Controller\\BilletController:index' => ['privates', '.service_locator.0c77nnS', 'get_ServiceLocator_0c77nnSService', true],
            'App\\Controller\\BilletController:new' => ['privates', '.service_locator.0c77nnS', 'get_ServiceLocator_0c77nnSService', true],
            'App\\Controller\\BilletController:show' => ['privates', '.service_locator.HCgIJYh', 'get_ServiceLocator_HCgIJYhService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\BilletController::delete' => '?',
            'App\\Controller\\BilletController::edit' => '?',
            'App\\Controller\\BilletController::index' => '?',
            'App\\Controller\\BilletController::new' => '?',
            'App\\Controller\\BilletController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\BilletController:delete' => '?',
            'App\\Controller\\BilletController:edit' => '?',
            'App\\Controller\\BilletController:index' => '?',
            'App\\Controller\\BilletController:new' => '?',
            'App\\Controller\\BilletController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
