<?php

namespace ContainerGwoi5jG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBillet2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.LjkgWYe.App\Entity\Billet' shared service.
     *
     * @return \App\Entity\Billet
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.LjkgWYe": it needs an instance of "App\\Entity\\Billet" but this type has been excluded in "config/services.yaml".');
    }
}
