<?php

namespace ContainerGwoi5jG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateCompanyCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\CreateCompanyCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\CreateCompanyCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('create-company', [], 'Creates a new company.', false, #[\Closure(name: 'App\\Command\\CreateCompanyCommand')] function () use ($container): \App\Command\CreateCompanyCommand {
            return ($container->privates['App\\Command\\CreateCompanyCommand'] ?? $container->load('getCreateCompanyCommandService'));
        });
    }
}
