<?php

namespace ContainerPjxbfja;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LjkgWYeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LjkgWYe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LjkgWYe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'billet' => ['privates', '.errored..service_locator.LjkgWYe.App\\Entity\\Billet', NULL, 'Cannot autowire service ".service_locator.LjkgWYe": it needs an instance of "App\\Entity\\Billet" but this type has been excluded in "config/services.yaml".'],
            'billetRepository' => ['privates', 'App\\Repository\\BilletRepository', 'getBilletRepositoryService', true],
        ], [
            'billet' => 'App\\Entity\\Billet',
            'billetRepository' => 'App\\Repository\\BilletRepository',
        ]);
    }
}
